CREATE TABLE "CAMPANHAS_OB"."CAMPANHA_PERGUNTA_OPCOES" (
    "ID_OPCAO"      SERIAL          PRIMARY KEY,
    "ID_PERGUNTAS"  INT             NOT NULL,
    "LABEL"         VARCHAR(500)    NOT NULL,
    "ORDEM"         INT             NOT NULL DEFAULT 0,
    "CREATED_AT"    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT"    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DELETED_AT"    TIMESTAMP       NULL,

    CONSTRAINT "FK_PERGUNTA_OPCOES_PERGUNTAS"
        FOREIGN KEY ("ID_PERGUNTAS")
        REFERENCES "CAMPANHAS_OB"."CAMPANHA_PERGUNTAS" ("ID_PERGUNTAS")
        ON DELETE CASCADE
);

CREATE INDEX "IDX_PERGUNTA_OPCOES_ID_PERGUNTAS"
    ON "CAMPANHAS_OB"."CAMPANHA_PERGUNTA_OPCOES" ("ID_PERGUNTAS");
