-- Migration: Notificação de Visita e Confirmação do Reparador
-- Data: 2026-08-05

CREATE TABLE IF NOT EXISTS "CAMPANHAS_OB"."NOTIFICACAO_VISITA" (
  "ID_NOTIFICACAO_VISITA" SERIAL PRIMARY KEY,
  "ID_ROTA_PROMOTOR" INT NOT NULL UNIQUE REFERENCES "CAMPANHAS_OB"."ROTA_PROMOTOR"("ID_ROTA_PROMOTOR"),
  -- ID_USUARIO / TOKEN_HASH / EXPIRA_EM are deliberately nullable: the row is INSERTed in
  -- PENDENTE (AC1) before a recipient is resolved (AC2) or a token issued (AC5), and the
  -- AC3 "no recipient with phone" path must be able to persist a FALHOU row with none of them.
  "ID_USUARIO" INT,
  "CANAL" VARCHAR(20) NOT NULL DEFAULT 'WHATSAPP',
  "STATUS" VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
  "TELEFONE_NORMALIZADO" VARCHAR(20),
  "TOKEN_HASH" VARCHAR(64),
  "EXPIRA_EM" TIMESTAMP,
  "ERRO_ENVIO" TEXT,
  "MESSAGE_ID" VARCHAR(100),
  "PROVIDER_MESSAGE_ID" VARCHAR(100),
  "ENVIADO_EM" TIMESTAMP,
  "CONFIRMADO_EM" TIMESTAMP,
  "CONFIRMADO_POR" INT,
  "CONFIRMADO_IP" VARCHAR(45),
  "ENDERECO_ATUALIZADO" BOOLEAN NOT NULL DEFAULT FALSE,
  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Supports the per-recipient anti-spam scan (NOTIF-28/29/30), which filters by
-- ID_USUARIO and STATUS on every route creation.
CREATE INDEX IF NOT EXISTS "IDX_NOTIFICACAO_VISITA_USUARIO_STATUS"
  ON "CAMPANHAS_OB"."NOTIFICACAO_VISITA" ("ID_USUARIO", "STATUS");

-- UNIQUE: TOKEN_HASH is the single-row lookup key for the exchange endpoint.
-- Postgres treats NULLs as distinct, so the nullable column above still allows
-- many un-issued (PENDENTE/FALHOU) rows to coexist.
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_NOTIFICACAO_VISITA_TOKEN_HASH"
  ON "CAMPANHAS_OB"."NOTIFICACAO_VISITA" ("TOKEN_HASH");
