ALTER TABLE "CAMPANHAS_OB"."CAMPANHA"
  ADD COLUMN IF NOT EXISTS "EMPRESA_SLUG" VARCHAR(100) NULL;

CREATE INDEX IF NOT EXISTS idx_campanha_empresa_slug
  ON "CAMPANHAS_OB"."CAMPANHA" ("EMPRESA_SLUG")
  WHERE "DELETED_AT" IS NULL;
