-- Importador de Oficinas (CON26-162)
-- Vínculo direto oficina->cliente, sem depender de usuário/comunidade.
-- Aplicar manualmente (sem runner de migration TypeORM neste repositório).

CREATE TABLE IF NOT EXISTS "CAMPANHAS_OB"."OFICINA_IMPORTADA" (
  "ID_OFICINA_IMPORTADA" SERIAL PRIMARY KEY,
  "ID_OFICINA" INT NOT NULL,
  "EMPRESA_SLUG" VARCHAR(100) NOT NULL,
  "ID_CAMPANHA" INT NULL,
  "CREATED_BY" INT NULL,
  "CREATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DELETED_AT" TIMESTAMP NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_oficina_importada_oficina_slug
  ON "CAMPANHAS_OB"."OFICINA_IMPORTADA" ("ID_OFICINA", "EMPRESA_SLUG")
  WHERE "DELETED_AT" IS NULL;

CREATE INDEX IF NOT EXISTS idx_oficina_importada_empresa_slug
  ON "CAMPANHAS_OB"."OFICINA_IMPORTADA" ("EMPRESA_SLUG")
  WHERE "DELETED_AT" IS NULL;
