-- Migration: Ordenação de Rotas de Oficinas para Promotores
-- Data: 2026-04-07

-- Novos campos em CAMPANHA_PROMOTOR
ALTER TABLE "CAMPANHAS_OB"."CAMPANHA_PROMOTOR"
  ADD COLUMN IF NOT EXISTS "ESTRATEGIA_ORDENACAO" VARCHAR(30) DEFAULT 'PROXIMIDADE_PROMOTOR',
  ADD COLUMN IF NOT EXISTS "ID_OFICINA_INICIO" INT NULL,
  ADD COLUMN IF NOT EXISTS "ID_OFICINA_FIM" INT NULL;

-- Novo campo em ROTA_PROMOTOR
ALTER TABLE "CAMPANHAS_OB"."ROTA_PROMOTOR"
  ADD COLUMN IF NOT EXISTS "ORDEM" INT NULL;
